/**
 *
 *  Course.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

using namespace drogon::orm;
namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace ptp_system 
{

class Course
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _course_name;
        static const std::string _teacher_id;
        static const std::string _start_time;
        static const std::string _end_time;
        static const std::string _student_group;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names, 
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all 
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Course(const Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Course(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Course(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Course() = default;
    
    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson, 
                          std::string &err, 
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;

    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;


    /**  For column course_name  */
    ///Get the value of the column course_name, returns the default value if the column is null
    const std::string &getValueOfCourseName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCourseName() const noexcept;

    ///Set the value of the column course_name
    void setCourseName(const std::string &pCourseName) noexcept;
    void setCourseName(std::string &&pCourseName) noexcept;


    /**  For column teacher_id  */
    ///Get the value of the column teacher_id, returns the default value if the column is null
    const int32_t &getValueOfTeacherId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getTeacherId() const noexcept;

    ///Set the value of the column teacher_id
    void setTeacherId(const int32_t &pTeacherId) noexcept;


    /**  For column start_time  */
    ///Get the value of the column start_time, returns the default value if the column is null
    const ::trantor::Date &getValueOfStartTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getStartTime() const noexcept;

    ///Set the value of the column start_time
    void setStartTime(const ::trantor::Date &pStartTime) noexcept;


    /**  For column end_time  */
    ///Get the value of the column end_time, returns the default value if the column is null
    const ::trantor::Date &getValueOfEndTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getEndTime() const noexcept;

    ///Set the value of the column end_time
    void setEndTime(const ::trantor::Date &pEndTime) noexcept;


    /**  For column student_group  */
    ///Get the value of the column student_group, returns the default value if the column is null
    const std::string &getValueOfStudentGroup() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStudentGroup() const noexcept;

    ///Set the value of the column student_group
    void setStudentGroup(const std::string &pStudentGroup) noexcept;
    void setStudentGroup(std::string &&pStudentGroup) noexcept;



    static size_t getColumnNumber() noexcept {  return 6;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend Mapper<Course>;
#ifdef __cpp_impl_coroutine
    friend CoroMapper<Course>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> courseName_;
    std::shared_ptr<int32_t> teacherId_;
    std::shared_ptr<::trantor::Date> startTime_;
    std::shared_ptr<::trantor::Date> endTime_;
    std::shared_ptr<std::string> studentGroup_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[6]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;                   
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;                   
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "course_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "teacher_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "start_time,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "end_time,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "student_group,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";
        
        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        } 
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;   
    }
};
} // namespace ptp_system
} // namespace drogon_model
