/**
 *
 *  PtpModule.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PtpModule.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::ptp_system;

const std::string PtpModule::Cols::_id = "id";
const std::string PtpModule::Cols::_module_name = "module_name";
const std::string PtpModule::Cols::_actions = "actions";
const std::string PtpModule::primaryKeyName = "id";
const bool PtpModule::hasPrimaryKey = true;
const std::string PtpModule::tableName = "ptp_module";

const std::vector<typename PtpModule::MetaData> PtpModule::metaData_={
{"id","int32_t","int",4,1,1,1},
{"module_name","std::string","varchar(255)",255,0,0,0},
{"actions","int32_t","int",4,0,0,1}
};
const std::string &PtpModule::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PtpModule::PtpModule(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["module_name"].isNull())
        {
            moduleName_=std::make_shared<std::string>(r["module_name"].as<std::string>());
        }
        if(!r["actions"].isNull())
        {
            actions_=std::make_shared<int32_t>(r["actions"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            moduleName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            actions_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

PtpModule::PtpModule(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            moduleName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());

        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            actions_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

PtpModule::PtpModule(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("module_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["module_name"].isNull())
        {
            moduleName_=std::make_shared<std::string>(pJson["module_name"].asString());
        }
    }
    if(pJson.isMember("actions"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["actions"].isNull())
        {
            actions_=std::make_shared<int32_t>((int32_t)pJson["actions"].asInt64());
        }
    }
}

void PtpModule::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            moduleName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            actions_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}
                                                                    
void PtpModule::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("module_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["module_name"].isNull())
        {
            moduleName_=std::make_shared<std::string>(pJson["module_name"].asString());
        }
    }
    if(pJson.isMember("actions"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["actions"].isNull())
        {
            actions_=std::make_shared<int32_t>((int32_t)pJson["actions"].asInt64());
        }
    }
}

const int32_t &PtpModule::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PtpModule::getId() const noexcept
{
    return id_;
}
void PtpModule::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}



const typename PtpModule::PrimaryKeyType & PtpModule::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &PtpModule::getValueOfModuleName() const noexcept
{
    const static std::string defaultValue = std::string();
    if(moduleName_)
        return *moduleName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PtpModule::getModuleName() const noexcept
{
    return moduleName_;
}
void PtpModule::setModuleName(const std::string &pModuleName) noexcept
{
    moduleName_ = std::make_shared<std::string>(pModuleName);
    dirtyFlag_[1] = true;
}
void PtpModule::setModuleName(std::string &&pModuleName) noexcept
{
    moduleName_ = std::make_shared<std::string>(std::move(pModuleName));
    dirtyFlag_[1] = true;
}


void PtpModule::setModuleNameToNull() noexcept
{
    moduleName_.reset();
    dirtyFlag_[1] = true;
}


const int32_t &PtpModule::getValueOfActions() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(actions_)
        return *actions_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PtpModule::getActions() const noexcept
{
    return actions_;
}
void PtpModule::setActions(const int32_t &pActions) noexcept
{
    actions_ = std::make_shared<int32_t>(pActions);
    dirtyFlag_[2] = true;
}




void PtpModule::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &PtpModule::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "module_name",
        "actions"
    };
    return inCols;
}

void PtpModule::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getModuleName())
        {
            binder << getValueOfModuleName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getActions())
        {
            binder << getValueOfActions();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PtpModule::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void PtpModule::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getModuleName())
        {
            binder << getValueOfModuleName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getActions())
        {
            binder << getValueOfActions();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PtpModule::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getModuleName())
    {
        ret["module_name"]=getValueOfModuleName();
    }
    else
    {
        ret["module_name"]=Json::Value();
    }
    if(getActions())
    {
        ret["actions"]=getValueOfActions();
    }
    else
    {
        ret["actions"]=Json::Value();
    }
    return ret;
}

Json::Value PtpModule::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getModuleName())
            {
                ret[pMasqueradingVector[1]]=getValueOfModuleName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getActions())
            {
                ret[pMasqueradingVector[2]]=getValueOfActions();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getModuleName())
    {
        ret["module_name"]=getValueOfModuleName();
    }
    else
    {
        ret["module_name"]=Json::Value();
    }
    if(getActions())
    {
        ret["actions"]=getValueOfActions();
    }
    else
    {
        ret["actions"]=Json::Value();
    }
    return ret;
}

bool PtpModule::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("module_name"))
    {
        if(!validJsonOfField(1, "module_name", pJson["module_name"], err, true))
            return false;
    }
    if(pJson.isMember("actions"))
    {
        if(!validJsonOfField(2, "actions", pJson["actions"], err, true))
            return false;
    }
    else
    {
        err="The actions column cannot be null";
        return false;
    }
    return true;
}
bool PtpModule::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PtpModule::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("module_name"))
    {
        if(!validJsonOfField(1, "module_name", pJson["module_name"], err, false))
            return false;
    }
    if(pJson.isMember("actions"))
    {
        if(!validJsonOfField(2, "actions", pJson["actions"], err, false))
            return false;
    }
    return true;
}
bool PtpModule::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PtpModule::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson, 
                                 std::string &err, 
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }        
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;               
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
