/**
 *
 *  PtpSubject.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PtpSubject.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::ptp_system;

const std::string PtpSubject::Cols::_id = "id";
const std::string PtpSubject::Cols::_student_id = "student_id";
const std::string PtpSubject::Cols::_course_id = "course_id";
const std::string PtpSubject::primaryKeyName = "id";
const bool PtpSubject::hasPrimaryKey = true;
const std::string PtpSubject::tableName = "ptp_subject";

const std::vector<typename PtpSubject::MetaData> PtpSubject::metaData_={
{"id","int32_t","int",4,1,1,1},
{"student_id","int32_t","int",4,0,0,0},
{"course_id","int32_t","int",4,0,0,0}
};
const std::string &PtpSubject::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PtpSubject::PtpSubject(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["student_id"].isNull())
        {
            studentId_=std::make_shared<int32_t>(r["student_id"].as<int32_t>());
        }
        if(!r["course_id"].isNull())
        {
            courseId_=std::make_shared<int32_t>(r["course_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            studentId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            courseId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

PtpSubject::PtpSubject(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            studentId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            courseId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

PtpSubject::PtpSubject(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("student_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["student_id"].isNull())
        {
            studentId_=std::make_shared<int32_t>((int32_t)pJson["student_id"].asInt64());
        }
    }
    if(pJson.isMember("course_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<int32_t>((int32_t)pJson["course_id"].asInt64());
        }
    }
}

void PtpSubject::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            studentId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            courseId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}
                                                                    
void PtpSubject::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("student_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["student_id"].isNull())
        {
            studentId_=std::make_shared<int32_t>((int32_t)pJson["student_id"].asInt64());
        }
    }
    if(pJson.isMember("course_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<int32_t>((int32_t)pJson["course_id"].asInt64());
        }
    }
}

const int32_t &PtpSubject::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PtpSubject::getId() const noexcept
{
    return id_;
}
void PtpSubject::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}



const typename PtpSubject::PrimaryKeyType & PtpSubject::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &PtpSubject::getValueOfStudentId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(studentId_)
        return *studentId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PtpSubject::getStudentId() const noexcept
{
    return studentId_;
}
void PtpSubject::setStudentId(const int32_t &pStudentId) noexcept
{
    studentId_ = std::make_shared<int32_t>(pStudentId);
    dirtyFlag_[1] = true;
}


void PtpSubject::setStudentIdToNull() noexcept
{
    studentId_.reset();
    dirtyFlag_[1] = true;
}


const int32_t &PtpSubject::getValueOfCourseId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(courseId_)
        return *courseId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PtpSubject::getCourseId() const noexcept
{
    return courseId_;
}
void PtpSubject::setCourseId(const int32_t &pCourseId) noexcept
{
    courseId_ = std::make_shared<int32_t>(pCourseId);
    dirtyFlag_[2] = true;
}


void PtpSubject::setCourseIdToNull() noexcept
{
    courseId_.reset();
    dirtyFlag_[2] = true;
}


void PtpSubject::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &PtpSubject::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "student_id",
        "course_id"
    };
    return inCols;
}

void PtpSubject::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getStudentId())
        {
            binder << getValueOfStudentId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PtpSubject::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void PtpSubject::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getStudentId())
        {
            binder << getValueOfStudentId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PtpSubject::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getStudentId())
    {
        ret["student_id"]=getValueOfStudentId();
    }
    else
    {
        ret["student_id"]=Json::Value();
    }
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    return ret;
}

Json::Value PtpSubject::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getStudentId())
            {
                ret[pMasqueradingVector[1]]=getValueOfStudentId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getCourseId())
            {
                ret[pMasqueradingVector[2]]=getValueOfCourseId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getStudentId())
    {
        ret["student_id"]=getValueOfStudentId();
    }
    else
    {
        ret["student_id"]=Json::Value();
    }
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    return ret;
}

bool PtpSubject::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("student_id"))
    {
        if(!validJsonOfField(1, "student_id", pJson["student_id"], err, true))
            return false;
    }
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(2, "course_id", pJson["course_id"], err, true))
            return false;
    }
    return true;
}
bool PtpSubject::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PtpSubject::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("student_id"))
    {
        if(!validJsonOfField(1, "student_id", pJson["student_id"], err, false))
            return false;
    }
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(2, "course_id", pJson["course_id"], err, false))
            return false;
    }
    return true;
}
bool PtpSubject::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PtpSubject::validJsonOfField(size_t index,
                                  const std::string &fieldName,
                                  const Json::Value &pJson, 
                                  std::string &err, 
                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }        
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
